export const TIER_FEATURES = {
  FREE: {
    name: "Free Trial",
    price: 0,
    estimatesPerMonth: 3,
    uploadsPerMonth: 0,
    promptToEstimate: true,
    promptToEdit: true,
    historicalUpload: false,
    pricingDNA: false,
    deviationAlerts: false,
    pdfExport: true,
    brandedPdf: false,
    logoUpload: false,
    winLossTracking: false,
    clientManagement: false,
    fullProposals: false,
    editableTerms: false,
    includeTerms: false,
    contractMode: false,
    clientInvoices: false,
    stripeConnect: false,
    proposalDefaults: false,
    projectPhotoProposal: false,
    logoWatermark: false,
  },
  STANDARD: {
    name: "Core",
    price: 49,
    annualPrice: 39,
    estimatesPerMonth: Infinity,
    uploadsPerMonth: 50,
    promptToEstimate: true,
    promptToEdit: true,
    historicalUpload: true,
    pricingDNA: true,
    deviationAlerts: true,
    pdfExport: true,
    brandedPdf: false,
    logoUpload: false,
    winLossTracking: false,
    clientManagement: false,
    fullProposals: false,
    editableTerms: true,
    includeTerms: true,
    contractMode: false,
    clientInvoices: false,
    stripeConnect: false,
    proposalDefaults: false,
    projectPhotoProposal: false,
    logoWatermark: false,
  },
  PRO: {
    name: "Pro",
    price: 99,
    annualPrice: 79,
    estimatesPerMonth: Infinity,
    uploadsPerMonth: Infinity,
    promptToEstimate: true,
    promptToEdit: true,
    historicalUpload: true,
    pricingDNA: true,
    deviationAlerts: true,
    pdfExport: true,
    brandedPdf: true,
    logoUpload: true,
    winLossTracking: true,
    clientManagement: true,
    fullProposals: false,
    editableTerms: true,
    includeTerms: true,
    contractMode: true,
    clientInvoices: false,
    stripeConnect: false,
    proposalDefaults: false,
    projectPhotoProposal: false,
    logoWatermark: false,
  },
  MAX: {
    name: "Max",
    price: 199,
    annualPrice: 159,
    estimatesPerMonth: Infinity,
    uploadsPerMonth: Infinity,
    promptToEstimate: true,
    promptToEdit: true,
    historicalUpload: true,
    pricingDNA: true,
    deviationAlerts: true,
    pdfExport: true,
    brandedPdf: true,
    logoUpload: true,
    winLossTracking: true,
    clientManagement: true,
    fullProposals: true,
    editableTerms: true,
    includeTerms: true,
    contractMode: true,
    clientInvoices: true,       // generate client invoices from estimates
    stripeConnect: true,         // accept card payments via Stripe Connect
    proposalDefaults: true,      // saved proposal templates (About Us, timeline, warranty)
    projectPhotoProposal: true,  // project photo on proposal cover page
    logoWatermark: true,         // logo watermark on proposal pages
  },
} as const

export type TierName = keyof typeof TIER_FEATURES

// Type for individual feature keys (boolean + numeric features)
export type TierFeatureKey = keyof (typeof TIER_FEATURES)["FREE"]

// Ordered tier list for comparison (index = rank)
export const TIER_ORDER: TierName[] = ["FREE", "STANDARD", "PRO", "MAX"]
