export const TIER_FEATURES = {
  FREE: {
    name: "Free Trial",
    price: 0,
    estimatesPerMonth: 10,
    uploadsPerMonth: 0,
    promptToEstimate: true,
    promptToEdit: true,
    historicalUpload: false,
    pricingDNA: false,
    deviationAlerts: false,
    pdfExport: true,
    brandedPdf: false,
    logoUpload: false,
    winLossTracking: false,
    clientManagement: false,
    fullProposals: false,
  },
  STANDARD: {
    name: "Standard",
    price: 19.99,
    annualPrice: 15.99,
    estimatesPerMonth: Infinity,
    uploadsPerMonth: 50,
    promptToEstimate: true,
    promptToEdit: true,
    historicalUpload: true,
    pricingDNA: true,
    deviationAlerts: true,
    pdfExport: true,
    brandedPdf: false,
    logoUpload: false,
    winLossTracking: false,
    clientManagement: false,
    fullProposals: false,
  },
  PRO: {
    name: "Pro",
    price: 29.99,
    annualPrice: 23.99,
    estimatesPerMonth: Infinity,
    uploadsPerMonth: Infinity,
    promptToEstimate: true,
    promptToEdit: true,
    historicalUpload: true,
    pricingDNA: true,
    deviationAlerts: true,
    pdfExport: true,
    brandedPdf: true,
    logoUpload: true,
    winLossTracking: true,
    clientManagement: true,
    fullProposals: false,
  },
  MAX: {
    name: "Max",
    price: 39.99,
    annualPrice: 31.99,
    estimatesPerMonth: Infinity,
    uploadsPerMonth: Infinity,
    promptToEstimate: true,
    promptToEdit: true,
    historicalUpload: true,
    pricingDNA: true,
    deviationAlerts: true,
    pdfExport: true,
    brandedPdf: true,
    logoUpload: true,
    winLossTracking: true,
    clientManagement: true,
    fullProposals: true,
  },
} as const

export type TierName = keyof typeof TIER_FEATURES

// Type for individual feature keys (boolean + numeric features)
export type TierFeatureKey = keyof (typeof TIER_FEATURES)["FREE"]

// Ordered tier list for comparison (index = rank)
export const TIER_ORDER: TierName[] = ["FREE", "STANDARD", "PRO", "MAX"]
