/**
 * Scope items available for each project type in Manual Selection mode.
 * Keys match PROJECT_TYPES[].key from project-types.ts.
 *
 * These are organized so builders can quickly tap what's in scope.
 * The AI uses selected + unselected items to understand scope boundaries.
 */
export const SCOPE_ITEMS: Record<string, string[]> = {
  kitchen_remodel: [
    "Demo",
    "Cabinets",
    "Countertops",
    "Backsplash",
    "Flooring",
    "Plumbing fixtures",
    "Electrical / GFCI",
    "Lighting",
    "Appliances",
    "Range hood / vent",
    "Painting",
    "Drywall repair",
    "Trim / Casing",
    "Island",
    "Pantry",
    "Permit",
  ],
  bathroom_remodel: [
    "Demo",
    "Vanity / Sink",
    "Toilet",
    "Shower / Tub",
    "Tile (floor)",
    "Tile (walls)",
    "Waterproofing",
    "Plumbing",
    "Electrical / GFCI",
    "Lighting",
    "Exhaust fan",
    "Mirror / Medicine cab",
    "Accessories",
    "Painting",
    "Heated floor",
    "Permit",
  ],
  full_home_renovation: [
    "Demo",
    "Framing",
    "Electrical rough",
    "Electrical finish",
    "Plumbing rough",
    "Plumbing finish",
    "HVAC",
    "Insulation",
    "Drywall",
    "Flooring",
    "Cabinets",
    "Countertops",
    "Painting",
    "Trim / Doors",
    "Fixtures",
    "Windows",
    "Exterior / Siding",
    "Roofing",
    "Permit",
  ],
  room_addition: [
    "Foundation",
    "Framing",
    "Roofing",
    "Siding",
    "Windows",
    "Exterior door",
    "Electrical",
    "Plumbing",
    "HVAC extension",
    "Insulation",
    "Drywall",
    "Flooring",
    "Painting",
    "Trim",
    "Structural eng.",
    "Permit",
  ],
  deck_patio: [
    "Footings / Piers",
    "Framing",
    "Decking (PT wood)",
    "Decking (composite)",
    "Railing",
    "Stairs",
    "Staining / Sealing",
    "Lighting",
    "Pergola / Cover",
    "Concrete patio",
    "Pavers",
    "Permit",
  ],
  basement_finish: [
    "Moisture barrier",
    "Framing",
    "Electrical",
    "Plumbing (bath rough)",
    "HVAC duct extension",
    "Insulation",
    "Drywall",
    "Flooring",
    "Egress window",
    "Bathroom finish",
    "Painting",
    "Trim / Doors",
    "Ceiling (drywall)",
    "Ceiling (drop)",
    "Sump pump",
    "Permit",
  ],
  new_construction: [
    // Site & Utilities
    "Site clearing",
    "Excavation",
    "Foundation",
    "Backfill / Grading",
    // Water supply
    "Drilled well",
    "Dug well",
    "Water utility connection",
    // Sewer
    "Septic system",
    "Sewer utility connection",
    // Power & Gas
    "Electrical service",
    "Gas service",
    // Structure
    "Framing",
    "Roofing",
    "Windows & Doors",
    "Siding / Exterior",
    // MEP rough
    "Plumbing rough",
    "Electrical rough",
    "HVAC",
    // Interior
    "Insulation",
    "Drywall",
    "Flooring",
    "Cabinets",
    "Countertops",
    "Painting",
    "Trim / Doors",
    "Fixtures",
    // Exterior
    "Paved driveway",
    "Gravel driveway",
    "Walkways",
    "Landscaping",
    "Garage",
    "Porch / Deck",
    "Permit",
  ],
  commercial_ti: [
    "Demo",
    "Framing / Layout",
    "Electrical",
    "Plumbing",
    "HVAC",
    "Fire protection",
    "Ceiling grid",
    "Flooring",
    "Painting",
    "Doors & hardware",
    "Storefront / Glass",
    "Millwork / Casework",
    "ADA compliance",
    "IT / Low voltage",
    "Signage",
    "Permit",
  ],
  roof_replacement: [
    "Tear-off (1 layer)",
    "Tear-off (2 layers)",
    "Sheathing repair",
    "Ice & water shield",
    "Underlayment",
    "Shingles (arch.)",
    "Metal roofing",
    "Flashing",
    "Ridge vent",
    "Drip edge",
    "Pipe boots",
    "Skylights",
    "Gutters",
    "Soffit / Fascia",
    "Dumpster",
    "Permit",
  ],
  window_replacement: [
    "Window removal",
    "Window install (vinyl)",
    "Window install (wood)",
    "Window install (fiberglass)",
    "Trim / Casing",
    "Flashing / Weatherproof",
    "Caulking",
    "Painting touch-up",
    "Storm windows",
    "Egress compliance",
    "Permit",
  ],
  siding_replacement: [
    "Removal",
    "Sheathing repair",
    "Housewrap",
    "Vinyl siding",
    "Fiber cement (Hardie)",
    "Wood siding",
    "Stone veneer",
    "Trim",
    "Soffit / Fascia",
    "Flashing",
    "Caulking",
    "Painting",
    "Permit",
  ],
  electrical_panel_upgrade: [
    "Panel replacement",
    "Meter base",
    "Main breaker",
    "Circuit reconnection",
    "New circuits",
    "Grounding / Bonding",
    "Utility coordination",
    "Surge protection",
    "Permit",
  ],
  hvac_replacement: [
    "Equipment removal",
    "Furnace",
    "AC condenser",
    "Heat pump",
    "Mini-split",
    "Ductwork",
    "Refrigerant lines",
    "Thermostat",
    "Electrical hookup",
    "Zoning system",
    "Permit",
  ],
  custom_other: [
    "Labor",
    "Materials",
    "Equipment",
    "Subcontractors",
    "Permits",
    "Dumpster / Hauling",
    "Engineering",
    "Miscellaneous",
  ],
}
